services:
  - type: web
    name: nexus
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://mxfbotvszuegnzuefznw.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 282207058325-v9sgc1n2a0j7sjde5nqgdbch2h1dg7nq.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
